start-at-login = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]        # force-maps, so workspaces never jump
1 = 1
2 = 2

# ------------------------------------------
# 3 · Key bindings – main mode
[mode.main.binding]
ctrl-alt-cmd-shift-space = 'focus-monitor --wrap-around next'   # cycle focus between monitors :contentReference[oaicite:0]{index=0}
ctrl-alt-cmd-shift-enter = 'focus right --boundaries-action wrap-around-the-workspace'
ctrl-alt-cmd-shift-tab    = 'move-node-to-monitor --wrap-around --focus-follows-window next'
