# ── Settings ───────────────────────────────────────────────
leader_key       = "f18"
leader_key_mods  = ""
auto_reload      = true
toast_on_reload  = true
show_ui          = true

# ── Group F : Music (leader-f) ────────────────────────────
[f]
label = "[Music]"

# Play / Pause
j = ["hs:mediaPlayPause()", "play"]

# Raycast search + next
k = ["raycast://extensions/mattisssa/spotify-player/search", "search"]
l = ["raycast://extensions/mattisssa/spotify-player/next","next"]

# ── Group M : Misc (leader-m) ─────────────────────────────
[m]
label = "[Misc]"

# E – three Gmail tabs
e = ["cmd:open 'https://mail.google.com/mail/u/0/#inbox' 'https://mail.google.com/mail/u/1/#inbox' 'https://mail.google.com/mail/u/2/#inbox'","email"]
